// This file is generated by GoAdmin CLI adm.

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "users" => http://localhost:9033/admin/info/users
// "patterns" => http://localhost:9033/admin/info/patterns
// "comments" => http://localhost:9033/admin/info/comments
//
// example end
package table

import (
	"github.com/GoAdminGroup/go-admin/context"
	"github.com/GoAdminGroup/go-admin/modules/db"
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
	"github.com/GoAdminGroup/go-admin/template/types/form"
)

// Map table keys to their generators
var Generators = map[string]table.Generator{
	"users":    GetUsersTable,
	"patterns": GetPatternsTable,
	"comments": GetCommentsTable,
}

// ------------------- Users Table -------------------
func GetUsersTable(ctx *context.Context) table.Table {
	users := table.NewDefaultTable(ctx, table.DefaultConfigWithDriver("postgresql"))

	info := users.GetInfo().HideFilterArea()
	info.SetTable("users").SetTitle("Users").SetDescription("Users Table")
	info.AddField("ID", "id", db.Numeric)
	info.AddField("Name", "name", db.Text)
	info.AddField("Email", "email", db.Text)
	info.AddField("Password Hash", "password_hash", db.Text)

	forms := users.GetForm()
	forms.SetTable("users").SetTitle("Users").SetDescription("Users Table")

	forms.AddField("Name", "name", db.Varchar, form.Text)
	forms.AddField("Email", "email", db.Varchar, form.Text)
	forms.AddField("Password Hash", "password_hash", db.Varchar, form.Password)

	return users
}

// ------------------- Patterns Table -------------------
func GetPatternsTable(ctx *context.Context) table.Table {
	patterns := table.NewDefaultTable(ctx, table.DefaultConfigWithDriver("postgresql"))

	info := patterns.GetInfo().HideFilterArea()
	info.SetTable("patterns").SetTitle("Patterns").SetDescription("Patterns Table")
	info.AddField("ID", "id", db.Numeric)
	info.AddField("User ID", "user_id", db.Numeric)
	info.AddField("Title", "title", db.Text)
	info.AddField("Created At", "created_at", db.Text)
	info.AddField("Width", "width", db.Numeric)
	info.AddField("Height", "height", db.Numeric)
	info.AddField("Diags", "diags", db.JSON)
	info.AddField("Is Public", "is_public", db.Bool)

	forms := patterns.GetForm()
	forms.SetTable("patterns").SetTitle("Patterns").SetDescription("Patterns Table")

	forms.AddField("User ID", "user_id", db.Int, form.Number)
	forms.AddField("Title", "title", db.Varchar, form.Text)
	forms.AddField("Created At", "created_at", db.Varchar, form.Text)
	forms.AddField("Width", "width", db.Int, form.Number)
	forms.AddField("Height", "height", db.Int, form.Number)
	forms.AddField("Diags", "diags", db.JSON, form.TextArea)
	forms.AddField("Is Public", "is_public", db.Bool, form.Switch)
	return patterns
}

// ------------------- Comments Table -------------------
func GetCommentsTable(ctx *context.Context) table.Table {
	comments := table.NewDefaultTable(ctx, table.DefaultConfigWithDriver("postgresql"))

	info := comments.GetInfo().HideFilterArea()
	info.SetTable("comments").SetTitle("Comments").SetDescription("Comments Table")
	info.AddField("ID", "id", db.Numeric)
	info.AddField("User ID", "user_id", db.Numeric)
	info.AddField("Pattern ID", "pattern_id", db.Numeric)
	info.AddField("Text", "text", db.Text)

	forms := comments.GetForm()
	forms.SetTable("comments").SetTitle("Comments").SetDescription("Comments Table")

	forms.AddField("User ID", "user_id", db.Int, form.Number)
	forms.AddField("Pattern ID", "pattern_id", db.Int, form.Number)
	forms.AddField("Text", "text", db.Varchar, form.TextArea)

	return comments
}
